"use client";

import { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import {
  Camera,
  Loader2,
  Copy,
  Check,
  Printer,
  ChevronDown,
  ChevronUp,
  Palette,
  Lightbulb,
  Users,
  Frame,
  Wand2,
} from "lucide-react";
import type { SavedShootBrief, ShootBriefResult } from "@/types/database";

const ANGLES = [
  "Product Hero",
  "Lifestyle",
  "Before/After",
  "Unboxing",
  "Flat Lay",
  "Behind the Scenes",
  "Founder Story",
  "Tutorial",
];

const TONES = [
  { value: "种草", sublabel: "Soft Sell" },
  { value: "干货", sublabel: "Educational" },
  { value: "故事", sublabel: "Storytelling" },
  { value: "搞笑", sublabel: "Funny" },
  { value: "高端", sublabel: "Luxury" },
  { value: "生活感", sublabel: "Lifestyle" },
];

interface ShootBriefClientProps {
  initialBriefs: SavedShootBrief[];
}

export function ShootBriefClient({ initialBriefs }: ShootBriefClientProps) {
  const [brandName, setBrandName] = useState("");
  const [productName, setProductName] = useState("");
  const [angle, setAngle] = useState("");
  const [tone, setTone] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<ShootBriefResult | null>(null);
  const [currentBrief, setCurrentBrief] = useState<{ brandName: string; productName: string; angle: string } | null>(null);
  const [briefs, setBriefs] = useState(initialBriefs);
  const [copied, setCopied] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const briefRef = useRef<HTMLDivElement>(null);

  async function handleGenerate() {
    if (!brandName.trim() || !productName.trim() || !angle) return;
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/shoot-brief", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ brandName: brandName.trim(), productName: productName.trim(), angle, tone }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error ?? "Generation failed"); return; }
      setResult(data.result as ShootBriefResult);
      setCurrentBrief({ brandName: brandName.trim(), productName: productName.trim(), angle });
      // Prepend to history
      if (data.briefId) {
        setBriefs((prev) => [{
          id: data.briefId,
          brand_name: brandName.trim(),
          product_name: productName.trim(),
          angle,
          result: data.result,
          created_at: new Date().toISOString(),
        }, ...prev.slice(0, 9)]);
      }
      setTimeout(() => {
        document.getElementById("brief-result")?.scrollIntoView({ behavior: "smooth" });
      }, 100);
    } catch {
      setError("Network error — please try again");
    } finally {
      setLoading(false);
    }
  }

  function compileBriefText(r: ShootBriefResult, meta: typeof currentBrief): string {
    const lines = [
      `SHOOT BRIEF — ${meta?.brandName} / ${meta?.productName}`,
      `Angle: ${meta?.angle}`,
      `Generated by RedBridge`,
      ``,
      `SCENE DESCRIPTION`,
      r.sceneDescription,
      ``,
      `PROPS`,
      ...r.propsList.map((p) => `• ${p}`),
      ``,
      `COLOUR PALETTE`,
      ...r.colourPalette.map((c) => `• ${c.name} — ${c.hex}`),
      ``,
      ...(r.modelDirection ? [`MODEL/TALENT DIRECTION`, r.modelDirection, ``] : []),
      `CAMERA & COMPOSITION`,
      r.cameraComposition,
      ``,
      `LIGHTING`,
      r.lightingDirection,
      ``,
      `CAPTION HOOKS`,
      ...r.captionHooks.map((h, i) => `${i + 1}. ${h}`),
      ``,
      `XHS TIPS`,
      ...r.xhsTips.map((t) => `• ${t}`),
      ``,
      `REFERENCE DESCRIPTION`,
      r.referenceDescription,
    ];
    return lines.join("\n");
  }

  function handleCopy() {
    if (!result || !currentBrief) return;
    navigator.clipboard.writeText(compileBriefText(result, currentBrief)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function handlePrint() {
    window.print();
  }

  function loadBrief(brief: SavedShootBrief) {
    setResult(brief.result);
    setCurrentBrief({ brandName: brief.brand_name, productName: brief.product_name, angle: brief.angle });
    setBrandName(brief.brand_name);
    setProductName(brief.product_name);
    setAngle(brief.angle);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  return (
    <>
      {/* Print styles — only the brief renders when printing */}
      <style>{`
        @media print {
          body * { visibility: hidden !important; }
          #brief-result, #brief-result * { visibility: visible !important; }
          #brief-result { position: fixed !important; inset: 0 !important; padding: 32px !important; background: white !important; color: black !important; }
          #brief-result .print\\:text-black { color: #000 !important; }
          #brief-result .colour-swatch { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
          @page { margin: 20mm; }
        }
      `}</style>

      <div className="space-y-6 md:space-y-8 print:hidden">
        <div>
          <h1 className="text-xl font-bold md:text-2xl">Shoot Brief Generator</h1>
          <p className="mt-1 text-sm text-[#6b7280]">
            Generate a complete photo/video brief for XHS content — scene, props, lighting, captions.
          </p>
        </div>

        {/* Form */}
        <div className="rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-6 space-y-5">
          <div className="flex items-center gap-2">
            <Camera size={13} className="text-[#ff2d55]" />
            <span className="font-mono text-xs uppercase tracking-widest text-[#ff2d55]">Brief Details</span>
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="brandName">Brand Name</Label>
              <Input
                id="brandName"
                value={brandName}
                onChange={(e) => setBrandName(e.target.value)}
                placeholder="e.g. Bondi Glow"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="productName">Product Name</Label>
              <Input
                id="productName"
                value={productName}
                onChange={(e) => setProductName(e.target.value)}
                placeholder="e.g. Vitamin C Serum"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="angle">Content Angle</Label>
            <Select value={angle} onValueChange={setAngle}>
              <SelectTrigger id="angle">
                <SelectValue placeholder="Select a content angle" />
              </SelectTrigger>
              <SelectContent>
                {ANGLES.map((a) => (
                  <SelectItem key={a} value={a}>{a}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label>
              Tone{" "}
              <span className="font-normal text-[#4a4a4a]">(optional)</span>
            </Label>
            <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">
              {TONES.map(({ value, sublabel }) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => setTone((prev) => (prev === value ? "" : value))}
                  className={cn(
                    "rounded-full border px-3 py-1.5 text-left transition-colors",
                    tone === value
                      ? "border-[#ff2d55] bg-[#ff2d55]/10 text-[#ff2d55]"
                      : "border-[#2a2a2a] bg-[#0d0d0d] text-[#6b7280] hover:border-[#3a3a3a] hover:text-white"
                  )}
                >
                  <span className="block font-mono text-xs">{value}</span>
                  <span className="block text-[10px] leading-tight">{sublabel}</span>
                </button>
              ))}
            </div>
          </div>

          {error && <p className="font-mono text-xs text-red-400">{error}</p>}

          <Button
            onClick={handleGenerate}
            disabled={loading || !brandName.trim() || !productName.trim() || !angle}
            className="w-full"
            size="lg"
          >
            {loading ? <Loader2 size={16} className="animate-spin" /> : <Wand2 size={16} />}
            {loading ? "Generating Brief…" : "Generate Shoot Brief"}
          </Button>
          <p className="font-mono text-xs text-[#3a3a3a]">Counts as 1 generation.</p>
        </div>
      </div>

      {/* Brief result */}
      {result && currentBrief && (
        <div id="brief-result" ref={briefRef} className="mt-6 md:mt-8 space-y-6 rounded-2xl border border-[#ff2d55]/20 bg-[#0d0d0d] p-4 sm:p-6 md:p-8">
          {/* Brief header */}
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between print:hidden">
            <div>
              <p className="font-mono text-xs uppercase tracking-widest text-[#ff2d55]">Shoot Brief</p>
              <h2 className="mt-1 text-lg font-bold text-white">
                {currentBrief.brandName} — {currentBrief.productName}
              </h2>
              <Badge variant="outline" className="mt-1.5 text-xs">{currentBrief.angle}</Badge>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={handleCopy}>
                {copied ? <Check size={13} /> : <Copy size={13} />}
                {copied ? "Copied!" : "Copy Brief"}
              </Button>
              <Button variant="outline" size="sm" onClick={handlePrint}>
                <Printer size={13} /> Print / PDF
              </Button>
            </div>
          </div>

          {/* Print header (only shown when printing) */}
          <div className="hidden print:block mb-6">
            <p style={{ color: "#ff2d55", fontFamily: "monospace", fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.15em" }}>
              RedBridge Shoot Brief
            </p>
            <h1 style={{ fontSize: "24px", fontWeight: "bold", margin: "4px 0" }}>
              {currentBrief.brandName} — {currentBrief.productName}
            </h1>
            <p style={{ color: "#555", fontSize: "13px" }}>{currentBrief.angle}</p>
          </div>

          <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
            {/* Scene description */}
            <div className="md:col-span-2 space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
              <SectionLabel icon={Frame} label="Scene Description" />
              <p className="text-sm leading-relaxed text-[#c0c0c0]">{result.sceneDescription}</p>
            </div>

            {/* Props */}
            <div className="space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
              <SectionLabel icon={Wand2} label="Props List" />
              <ul className="space-y-1.5">
                {result.propsList.map((prop, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-[#c0c0c0]">
                    <span className="mt-0.5 font-mono text-[#ff2d55] text-xs">•</span>
                    {prop}
                  </li>
                ))}
              </ul>
            </div>

            {/* Colour palette */}
            <div className="space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
              <SectionLabel icon={Palette} label="Colour Palette" />
              <div className="grid grid-cols-2 gap-2">
                {result.colourPalette.map((colour) => (
                  <div key={colour.hex} className="flex items-center gap-2.5">
                    <div
                      className="colour-swatch h-8 w-8 shrink-0 rounded-lg border border-[#2a2a2a]"
                      style={{ backgroundColor: colour.hex }}
                    />
                    <div>
                      <p className="text-xs font-medium text-white">{colour.name}</p>
                      <p className="font-mono text-[10px] text-[#4a4a4a]">{colour.hex}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Camera & composition */}
            <div className="space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
              <SectionLabel icon={Camera} label="Camera & Composition" />
              <p className="text-sm leading-relaxed text-[#c0c0c0]">{result.cameraComposition}</p>
            </div>

            {/* Lighting */}
            <div className="space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
              <SectionLabel icon={Lightbulb} label="Lighting Direction" />
              <p className="text-sm leading-relaxed text-[#c0c0c0]">{result.lightingDirection}</p>
            </div>

            {/* Model direction */}
            {result.modelDirection && (
              <div className="space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
                <SectionLabel icon={Users} label="Model / Talent Direction" />
                <p className="text-sm leading-relaxed text-[#c0c0c0]">{result.modelDirection}</p>
              </div>
            )}

            {/* Caption hooks */}
            <div className="md:col-span-2 space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
              <SectionLabel icon={Wand2} label="Caption Hooks" />
              <div className="space-y-2">
                {result.captionHooks.map((hook, i) => (
                  <div key={i} className="flex items-start gap-3 rounded-lg border border-[#1a1a1a] bg-[#0d0d0d] p-3">
                    <span className="shrink-0 font-mono text-xs text-[#ff2d55] mt-0.5">{i + 1}.</span>
                    <p className="text-sm leading-relaxed text-white">{hook}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* XHS tips */}
            <div className="space-y-2 rounded-xl border border-[#ff2d55]/10 bg-[#ff2d55]/5 p-4 sm:p-5">
              <p className="font-mono text-[10px] uppercase tracking-widest text-[#ff2d55]">XHS Visual Tips</p>
              <ul className="space-y-2">
                {result.xhsTips.map((tip, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-[#c0c0c0]">
                    <span className="mt-0.5 text-[#ff2d55] font-mono text-xs">→</span>
                    {tip}
                  </li>
                ))}
              </ul>
            </div>

            {/* Reference */}
            <div className="space-y-2 rounded-xl border border-[#1a1a1a] bg-[#111] p-4 sm:p-5">
              <p className="font-mono text-[10px] uppercase tracking-widest text-[#4a4a4a]">Reference Description</p>
              <p className="text-sm leading-relaxed italic text-[#6b7280]">{result.referenceDescription}</p>
            </div>
          </div>
        </div>
      )}

      {/* History */}
      {briefs.length > 0 && (
        <div className="print:hidden mt-6 rounded-xl border border-[#1a1a1a] bg-[#0d0d0d] overflow-hidden">
          <button
            type="button"
            onClick={() => setHistoryOpen((o) => !o)}
            className="flex w-full items-center justify-between px-5 py-4 text-left transition-colors hover:bg-[#111]"
          >
            <span className="font-mono text-xs uppercase tracking-widest text-[#4a4a4a]">
              Saved Briefs ({briefs.length})
            </span>
            {historyOpen ? (
              <ChevronUp size={13} className="text-[#4a4a4a]" />
            ) : (
              <ChevronDown size={13} className="text-[#4a4a4a]" />
            )}
          </button>
          {historyOpen && (
            <div className="border-t border-[#1a1a1a] divide-y divide-[#1a1a1a]">
              {briefs.map((brief) => (
                <button
                  key={brief.id}
                  type="button"
                  onClick={() => loadBrief(brief)}
                  className="flex w-full items-center justify-between px-5 py-3.5 text-left transition-colors hover:bg-[#111] group"
                >
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium text-white group-hover:text-[#ff2d55] transition-colors">
                      {brief.brand_name} — {brief.product_name}
                    </p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <Badge variant="secondary" className="text-[10px] px-1.5 py-0">{brief.angle}</Badge>
                      <span className="font-mono text-[10px] text-[#4a4a4a]">
                        {new Date(brief.created_at).toLocaleDateString("en-AU")}
                      </span>
                    </div>
                  </div>
                  <span className="font-mono text-xs text-[#ff2d55] shrink-0 ml-3 opacity-0 group-hover:opacity-100 transition-opacity">
                    Load →
                  </span>
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </>
  );
}

function SectionLabel({ icon: Icon, label }: { icon: typeof Camera; label: string }) {
  return (
    <div className="flex items-center gap-2">
      <Icon size={12} className="text-[#4a4a4a]" />
      <p className="font-mono text-[10px] uppercase tracking-widest text-[#4a4a4a]">{label}</p>
    </div>
  );
}
